services:
    www:
        image: viratco/portfolio:1.0
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html/:cached  # Added :cached for better performance on macOS
        links:
            - db
        networks:
            - default

    db:
        image: mysql:8.0
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: virat
            MYSQL_USER: virat
            MYSQL_PASSWORD: virat@10
            MYSQL_ROOT_PASSWORD: virat@10
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "82:80"
        platform: linux/amd64
        environment:
            MYSQL_USER: virat
            MYSQL_PASSWORD: virat@10
            MYSQL_ROOT_PASSWORD: virat@10

volumes:
    persistent:
